### ISSUE TITLE
Allow to replace a Scene with another one

### ISSUE THREAD

**Issue by maicol07** [EasyG0ing1/SceneOneFX#2]
Hi,
can you add a method to allow to replace a scene with another one (i.e. a `replace(sceneId)` method?) or a way to set a stage of a scene (maybe better)?
Thanks

**Comment by EasyG0ing1** [comment]
Hi @maicol07 - Are you basically talking about swapping out a scene on the same stage that another scene is currently using? 

The predecessor to this library use to have a feature in it where you could assign a stage and then tell it to use that stage for all Scenes ... perhaps I should put that in this library, in addition to replace - which is a great idea.

**Comment by EasyG0ing1** [comment]
@maicol07 - Currently, the library has a method called setParent, which almost does exactly what you want. It takes the parent object, creates a new scene, then it assigns the new Scene to the existing Stage. It only works on existing scenes.

```java
SceneOne.setParent(sceneId, parent);
```

However, it's easy enough to add a method where you pass it a scene that gets swapped out on the existing stage.

**Comment by EasyG0ing1** [comment]
@maicol07 
OK, I added the swapScene method, and also added to Builder starters so you can start a SceneOne instance by passing it a Scene in addition to a Parent.

```java
SceneOne.swapScene(sceneId, stage);
SceneOne.set(sceneId, stage).build();
SceneOne.set(sceneId, stage, width, height).build();
```

Updated to version 1.2.2 and already pushed it out to the Maven repo so it should be available from your preferred builder in about an hour from now I believe.
